### ISSUE TITLE
Update README

### ISSUE THREAD

**Issue by GentrySteven** [DLFMetadataAssessment/DLFMetadataAssessment.github.io#106]
To be completed once the Sandbox has been merged into the main site, or at another time as determined by the group:

Using the README template in the Documentation Project Plan, update the production site's README file.

Can be done by one of the three members of the Documentation sub-group (Gabi, Staci, or Steven).

**Comment by kateefly** [comment]
Resolved by commit 33208ff92c58caadb3f726e6808ee605bb88b05b
