### ISSUE TITLE
Update main site with what's currently on Sandbox

### ISSUE THREAD

**Issue by kateefly** [DLFMetadataAssessment/DLFMetadataAssessment.github.io#130]
This involves:

-  Moving the code over from Sandbox
- Updating links as needed
- Deactivating no longer user repositories

**Comment by sgolds15** [comment]
Hi @kateefly! Sorry I didn’t see this earlier, I must have missed the second notification. This looks good, but would it be possible to (1) comment out or delete the `baseurl: /Sandbox` line in the _config.yml file (on production only), and (2) do a `git rm` (or `git rm --cached`) on the Gemfile.lock file? Thanks!
