### ISSUE TITLE
Correct Link on Presentations Page

### ISSUE THREAD

**Issue by htarver** [DLFMetadataAssessment/DLFMetadataAssessment.github.io#148]
The citation for the first presentation of note (http://dlfmetadataassessment.github.io/projects/publications/) is incorrect:

Averkamp, Shawn, Matt Miller, Josh Hadro, and Sara Rubinow. “Measuring Your Metadata Preconference.” Presentations (communicative events) presented at the Code4Lib Philadelphia, March 7-10 2016, Philadelphia, PA, USA, March 7, 2016. http://digital.library.unt.edu/ark:/67531/metadc505014.

That link is actually an alternate link for the last publication listing (Zavalina, Oksana L., Priya Kizhakkethil, Daniel Gelaw Alemneh, Mark E. Phillips, and Hannah Tarver. “Building a Framework of Metadata Change to Support Knowledge Management.” Journal of Information & Knowledge Management 14, no. 01 (March 1, 2015). https://doi.org/10.1142/S0219649215500057.)

There is a link for the presentation, but I'm not sure if the link should be the conference page for the event (https://2016.code4lib.org/workshops/Measuring-Your-Metadata), or the GitHub repository for the actual materials (https://github.com/saverkamp/measure-metadata-workshop).

**Comment by agoslen** [comment]
Thank you @htarver . I've emailed the preconference presenters to see what link they would prefer.

**Comment by agoslen** [comment]
@htarver The presenters didn't have a link preference, so we're going to update the link to point to the GitHub repository (https://github.com/saverkamp/measure-metadata-workshop). We thought that might be more likely to remain stable than the conference event page. We'll make the change on the Sandbox (via [this issue](https://github.com/DLFMetadataAssessment/Sandbox/issues/322)), and then the change would make its way to the main site in the fall. Let us know however if there is a preference that the change be reflected on the main site in a more timely manner and we can do that!

**Comment by agoslen** [comment]
This is now fixed: https://dlfmetadataassessment.github.io/projects/publications/
