### ISSUE TITLE
Add information about workflow & best practices to Readme?

### ISSUE THREAD

**Issue by kateefly** [DLFMetadataAssessment/DLFMetadataAssessment.github.io#16]
From our call, these are the three best practices and workflow issues we discussed. I propose that we add them to the Readme.

- Work should be done in new branches based on issue and not dev or master branches

- Once you are done, please submit a pull request for another member of the group to review and merge into master

- If a pull request takes a while to be merged into the master branch, you can send a message to the Google Group asking for someone to review your changes

**Comment by cmh2166** [comment]
merge this with readme.md ASAP.

**Comment by cmh2166** [comment]
Like an idiot, I added this best practices then without thinking merge automatically into the readme.md. Entirely my bad. Can push a revert and then a proper PR if the group prefers, which will result in a few PRs.

**Comment by kateefly** [comment]
No need to revert, this looks ok as is.
