### ISSUE TITLE
Add dynamic Tools summary pie charts

### ISSUE THREAD

**Issue by kgrons** [DLFMetadataAssessment/DLFMetadataAssessment.github.io#34]
Work on adding two pie charts from Tools working spreadsheet (https://drive.google.com/folderview?id=0B74oOQcTdnHjWk51a283bUVta0E&usp=sharing) PieCharts tab to Tools entry on the site.

When static versions of these are added, we can only a new issue for figuring out how to add them as dynamic graphics.

**Comment by kgrons** [comment]
FYI - Pie charts have been updated as of today in their tab (dates added to chart titles).

**Comment by kateefly** [comment]
Note: This issue refers to dynamic pie charts that would be updated automatically as the spreadsheet. There will be static versions as part of issue #43 .
