### ISSUE TITLE
List of Contributors on site

### ISSUE THREAD

**Issue by aneatrour** [DLFMetadataAssessment/DLFMetadataAssessment.github.io#37]
Hi, I was wondering if we should have a list of contributors to the group on the site. Any thoughts about this?

**Comment by kateefly** [comment]
I think this would be a good idea, especially for those who need something to point to for tenure or promotion reviews. Would we want to divide this up to show specific contributions (people who worked on the working document, people who worked on the Github site, etc) or just do a general list of contributors?

**Comment by aneatrour** [comment]
I think a general list of contributors would be fine, and probably easier to manage, but if other people want something with defined contributions that's ok by me. Having something to point to for reviews would be very helpful. Maybe we could just start a google doc with a list, that we could push over to this site?

**Comment by cmh2166** [comment]
Wendy Robertson
Anna Goslen
Amber Sherman
Amelia Mowry
Anna Neatrour
Ayla Stein
Angelina Zaytsev
Bill McMillin
Bria Parker
Christina Harlow
Dana Jemison
Laura Drake Davis
Domenic Rosati
Hannah Tarver
Debra Shapiro
Anne Caldwell
Ethan Fenichel
Filipe Bento
Friday Valentine
Hilary Robbeloth
Violeta Ilik
Ivey Glendon
Jennifer Young
Kevin Clair
Jason Roy
Jennifer Gilbert
Jeremy Myntti
Janet Ahrberg
Joyce Chapman
Kathryn Stine
Kate Flynn
Kathryn Gronsbell
Kayla Ondracek
Lukas Koster
Laura Smart
Andrea Leonard
Liz Kupke
Liz Woolcott
Maggie Dickson
Karen Majewicz
Melissa Rucker
Molly Bragg
Arcadia Falcone
Peggy Griesinger
Patrick Galligan
Rachel Trent
Erik Radio
Robin Desmeules
Sarah Potvin
Sara Rubinow
Matt Schultz
Sarah Beth Seymore
Sharon Farnel
Shaun Akhtar
Shawn Averkamp
Sibyl Schaefer
Sam Popowich
Timothy Ryan Mendenhall
Jennifer Eustis
Wendy Hagenmaier
Tracy Chui

**Comment by cmh2166** [comment]
That's the list of names from the email group as best I could pull and figure out where people didn't include a name. I've removed those asking to be removed. Needs to be sorted and possibly deduped.
