### ISSUE TITLE
Tools Overview Sheet table & Details Sheet look very similar

### ISSUE THREAD

**Issue by kateefly** [DLFMetadataAssessment/DLFMetadataAssessment.github.io#38]
The last merge fixed the table formatting issue, however the Tools Overview sheet table is now appearing twice.

**Comment by cmh2166** [comment]
Add text to help differentiate the different tables information / metadata.

**Comment by cmh2166** [comment]
@f8f8ff + @aneantrour will add context for information for this section. + maybe follow up the pie charts. Involves 2 other issues.

**Comment by kgrons** [comment]
Tool Overview and Tool Details data combined today in the Tool Overview tab. 

Following review by @f8f8ff we will delete OLD Tool Details tab from document.

**Comment by f8f8ff** [comment]
Updated Tools Overview tab looks good. Suggest creating new internal-facing sheet from OLD Tools Details tab to retain/track information about who is reviewing what tool.

**Comment by cmh2166** [comment]
Move to issue #43 . Text / tables have been cleaned up.
