### ISSUE TITLE
add citations list to the bottom of site

### ISSUE THREAD

**Issue by cmh2166** [DLFMetadataAssessment/DLFMetadataAssessment.github.io#39]

**Comment by kateefly** [comment]
Just let me know what list to work off of and I can take care of this.

**Comment by kateefly** [comment]
Generated from Zotero, also include presentations, tools, everything.

**Comment by kateefly** [comment]
Do we want this list to adhere to any specific format (MLA, etc) or is the semi-casual formatting we were using in the environmental scan ok?

**Comment by cmh2166** [comment]
We discussed this a few meetings ago, and I believe everyone present was good with generic formatting (just _creator. title. date. link_ type thing)

**Comment by cmh2166** [comment]
(or whatever is easiest to generate)

**Comment by maggiedickson** [comment]
yeah that makes sense to me, simple is good!

**Comment by maggiedickson** [comment]
So, the list will contain a citation for every single resource we reference on the site, in all the various sections, is that correct? How do we want it organized? Alphabetically? Or by resource type, then alphabetically?

**Comment by cmh2166** [comment]
Merged fix.
