### ISSUE TITLE
Revise "Take part" Section

### ISSUE THREAD

**Issue by kateefly** [DLFMetadataAssessment/DLFMetadataAssessment.github.io#53]
- Add last updated to this section (even if it's just in text)

- Add link to Google form as the way people can suggest edits, additions, etc. Put in note that these suggestions are reviewed quarterly.

- Link to Google group for people to join if they are interested

- Leave link to DLF wiki

- Remove all other links

**Comment by cmh2166** [comment]
updated per #56

**Comment by kateefly** [comment]
Resolved with 57df0b924cebee8b20d75da93b9ab14004c19fed and 99a4e517e723b111217413f2e9e36d2930e83a44
