### ISSUE TITLE
Review code to make sure it matches GFM spec

### ISSUE THREAD

**Issue by kateefly** [DLFMetadataAssessment/DLFMetadataAssessment.github.io#54]
It should be ok but we don't want to be surprised.

Spec is here: https://github.github.com/gfm/

**Comment by cmh2166** [comment]
What is this wanting to achieve rn (i.e. have there been Markdown appearance errors in the jekyll creation)? If we're looking to migrate to the new site for the emerging toolkit work, we will want to minimize any changes here to the markdown (basically, just docs/README), imho.

**Comment by kateefly** [comment]
See this blog post. Github.com is now using their own spec to render markdown: https://github.com/blog/2333-a-formal-spec-for-github-flavored-markdown

I think this will basically be a quick review to make sure nothing is broken as a result of this change and that this ticket is documentation that we did this.

**Comment by kateefly** [comment]
Did a review and everything looks ok
