### ISSUE TITLE
Add information to Tools section of Review page from Main Working Document

### ISSUE THREAD

**Issue by kateefly** [DLFMetadataAssessment/DLFMetadataAssessment.github.io#7]
This would be the information contained in this section of the Main Working Document: [https://docs.google.com/document/d/1rk6TThrSqpLNk-L0JgR3lk5b_M3M8n5xM2xggKHYVUw/edit#heading=h.nte3qkd91px7](https://docs.google.com/document/d/1rk6TThrSqpLNk-L0JgR3lk5b_M3M8n5xM2xggKHYVUw/edit#heading=h.nte3qkd91px7)

**Comment by kgrons** [comment]
Any recommendations for how to display the breakdown of info in the [Tools spreadsheet](https://docs.google.com/spreadsheets/d/1PCi_3pcWSFQ9fR54AxwO7LWuBUu2vbVw1etvw_UAl5g/edit?usp=sharing) (which has more complete info than what is in the Main Working Document)? Overview tab has general information, Details tab has additional characteristics of each tool/language selected.

**Comment by kgrons** [comment]
Per meeting on 6/16/2016, I will add:

- Sampling of tools/etc reviewed (and numbering rationale)
- Link out to spreadsheet (with overview of what’s included)
- Include static pie chart graphics in overview

**Comment by kgrons** [comment]
Closing this issue per today's PR merge - new issue created to address pie chart additions.
