### ISSUE TITLE
Links on metadata benchmarks page - survey and spreadsheet

### ISSUE THREAD

**Issue by aneatrour** [DLFMetadataAssessment/DLFMetadataAssessment.github.io#72]
Hi, I think I made a mistake with the links on the metadata benchmarks page. I can see that the files I added uploaded to the repository just fine, but I think due to my lack of understanding of the proper relative link structure, the links to the files are 404ing, like this: http://dlfmetadataassessment.github.io/assets/SurveyofMetadataQualityBenchmarks.pdf

Any tips for what I should do to fix this? Thanks for the help!!!

**Comment by kateefly** [comment]
I think what happened was that there were two branches with update information for the Benchmarks page and that they conflicted. One included updated text and the other included the pdf/spreadsheet but only one got merged into master. I can make sure both updates are applied if the files are sent to me and @RachelJaneWittmann can confirm that the text that is currently on the site is correct?

**Comment by kateefly** [comment]
Resolved by commit 999229456dab1b94355784df7d3fc60a7a22ea40
