### ISSUE TITLE
Link to “[...] please see the Take Part section” in Presentations section of Environmental Scan is not working

### ISSUE THREAD

**Issue by kateefly** [DLFMetadataAssessment/DLFMetadataAssessment.github.io#79]
Link is http://dlfmetadataassessment.github.io/EnvironmentalScan#take-part should be http://dlfmetadataassessment.github.io/Take-Part

**Comment by plampron2** [comment]
I don't know if I'm supposed to close this or not, but I merged the pull request that fixed this issue (https://github.com/DLFMetadataAssessment/DLFMetadataAssessment.github.io/pull/91)

**Comment by kateefly** [comment]
This is ok to close - everything looks good! Thanks @eightBitter and @plampron2
