### ISSUE TITLE
Implement docster theme

### ISSUE THREAD

**Issue by billmcmillin** [DLFMetadataAssessment/DLFMetadataAssessment.github.io#8]
http://digitalmind.ch/themes/docster-jekyll-theme/demo/

**Comment by cmh2166** [comment]
I've got this partially done, will push to dev branch later.

**Comment by billmcmillin** [comment]
cool. Let me know if I can help with anything.

**Comment by cmh2166** [comment]
I've got the starter for the implementation up and stable enough for the master branch. take a look and see what updates can occur (besides getting the content done/migrated). Thanks!

**Comment by billmcmillin** [comment]
Looks great!
