### ISSUE TITLE
Link "Data Quality Committee" is not working

### ISSUE THREAD

**Issue by GentrySteven** [DLFMetadataAssessment/DLFMetadataAssessment.github.io#83]
Under "Organizations & Groups" and "Europeana"

https://pro.europeana.eu/page/data-quality-committee is the broken link. Should it be https://pro.europeana.eu/project/data-quality-committee?

**Comment by kateefly** [comment]
@GentrySteven I agree that looks right.

**Comment by GentrySteven** [comment]
Closed via #101
