### ISSUE TITLE
Hydra Groups Links Behind Login

### ISSUE THREAD

**Issue by GentrySteven** [DLFMetadataAssessment/DLFMetadataAssessment.github.io#84]
Under "Organizations & Groups" and "Hydra Groups"

All links--excluding the single "Samvera" link--now direct the user to a login screen

**Comment by kateefly** [comment]
New links to Samvera Groups: https://wiki.lyrasis.org/display/samvera/Interest+Group+%28IG%29+and+Working+Group+%28WG%29+Hub

Link to the Metadata Interest Group specifically: https://wiki.lyrasis.org/display/samvera/Samvera+Metadata+Interest+Group

**Comment by GentrySteven** [comment]
Closed via #101
