### ISSUE TITLE
Link to "Final Report of the Task Force on Cost/Value Assessment of Bibliographic Control" is broken

### ISSUE THREAD

**Issue by GentrySteven** [DLFMetadataAssessment/DLFMetadataAssessment.github.io#85]
Under "Organizations & Groups" and "ALA ALCTS “Big Heads”

https://connect.ala.org/files/7981/costvaluetaskforcereport2010_06_18_pdf_77542.pdf this link is broken

**Comment by kateefly** [comment]
So this link worked: https://connect.ala.org/HigherLogic/System/DownloadDocumentFile.ashx?DocumentFileKey=aa0c09ad-a682-4e86-b5e7-106ea84b98d1&forceDialog=0

But I'm very nervous as to whether or not this link will persist. Will continue trying to look for a more stable link.

**Comment by kateefly** [comment]
So there's an article on this report in Library Resources & Technical Services, v. 55, no.3 (July 2011) called "Assessing the Cost and Value of Bibliographic Control" by Erin Stalberg & Christopher Cronin. This is behind a paywall but may be a more stable way of referring to the outputs of this committee than the link to the report. Whether or not this happens, definitely requires further review.

**Comment by GentrySteven** [comment]
How about this one? I had to try a few links in the Wayback Machine, but this--at first glance--looks to be the same report?

https://web.archive.org/web/20171007134005/https://connect.ala.org/files/7981/costvaluetaskforcereport2010_06_18_pdf_77542.pdf

**Comment by kateefly** [comment]
Please use Wayback Machine link.

**Comment by GentrySteven** [comment]
Closed via #101
