### ISSUE TITLE
"ALCTS/LITA Metadata Standards" links now redirect to another site

### ISSUE THREAD

**Issue by GentrySteven** [DLFMetadataAssessment/DLFMetadataAssessment.github.io#86]
Under "Organizations & Groups" and "ALCTS/LITA Metadata Standards"

Both http://metaware.buzz/2015/10/27/draft-principles-for-evaluating-metadata-standards/ now and http://metaware.buzz/2016/04/18/summary-of-comments-received-on-msc-principles-for-evaluating-metadata-standards/ redirect to another website.

**Comment by str51** [comment]
Wayback of first url (Mar 3, 2016): https://web.archive.org/web/20160303095702/http://metaware.buzz/2015/10/27/draft-principles-for-evaluating-metadata-standards/

2nd url (Apr 18, 2016): https://web.archive.org/web/20160918105442/http://metaware.buzz/2016/04/18/summary-of-comments-received-on-msc-principles-for-evaluating-metadata-standards/

**Comment by mbolam** [comment]
In a "while we're at it" situation - this is the final version of "The Principles", which must have been released after the 
original Env Scan. 
https://web.archive.org/web/20180915041307/http://metaware.buzz/2016/08/04/principles-for-evaluating-metadata-standards/

**Comment by kateefly** [comment]
Include both first link and last link. Include contextual info that the first was what was evaluated as part of scan but last is most current.

**Comment by GentrySteven** [comment]
Closed via #101
